#!/bin/sh

THIS_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "Relativistic Band Structure of Phosphorene"
$ECHO 

# set quantum espresso path
. qe-path
# set environment variables path
ENV_PATH=$QE_PATH/environment_variables
# set the needed environment variables
. $ENV_PATH
# override pseudopotential path
PSEUDO_DIR=$THIS_DIR/pseudo

# required executables and pseudopotentials
BIN_LIST="pw.x bands.x"
PSEUDO_LIST="P.rel-pbe-nl-rrkjus_psl.1.0.0.UPF"
TMP_ROOT_DIR="$THIS_DIR/temp"
TMP_DIR="$THIS_DIR/temp/relativistic"
IN_DIR="$THIS_DIR/in"
OUT_DIR="$THIS_DIR/out/relativistic"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "\n  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_ROOT_DIR" "$TMP_DIR" "$OUT_DIR" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $OUT_DIR

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
BANDS_COMMAND="$PARA_PREFIX $BIN_DIR/bands.x $PARA_POSTFIX"

$ECHO
$ECHO "  running pw.x as:       $PW_COMMAND"
$ECHO "  running bands.x as:    $BANDS_COMMAND"
$ECHO

# set paramters
atom='P'
prefix='phosphorene'
ecutwfc=34.0
num_k=12
soc='.TRUE.'
efield='.FALSE.'
efield_amp=0.0
pseudo='P.rel-pbe-nl-rrkjus_psl.1.0.0.UPF'
num_band=32

# run scf calculation 
. $IN_DIR/scf
# run non scf calculation 
. $IN_DIR/nscf    
# run band structure calculation along high-symmetry lines
. $IN_DIR/band
# post processing bands 
. $IN_DIR/bands

# end of file