#!/bin/sh

cat > $prefix.scf.in <<EOF
 &control
  calculation = 'scf'
  title = 'Self-consistent field calculation of $prefix'
  verbosity = 'high'
  restart_mode = 'from_scratch'
  outdir ='$TMP_DIR/'
  prefix ='$prefix'
  pseudo_dir = '$PSEUDO_DIR/'
  tprnfor = .TRUE.
  lelfield = $efield
  nberrycyc = 1
 /
 &system
  ibrav = 8
  celldm(1) = 8.404
  celldm(2) = 0.756
  celldm(3) = 10.0 
  nat = 4 
  ntyp = 1 
  nbnd = $num_band
  ecutwfc = $ecutwfc
  occupations = 'fixed' 
  lspinorb = $soc
  noncolin = $soc
  starting_magnetization = 0.0
 /
 &electrons
  electron_maxstep = 100
  conv_thr = 1.0d-6
  mixing_mode = 'plain'
  mixing_beta = 0.3d0
  diagonalization = 'david'
  diago_full_acc = .TRUE.
  efield_cart(1) = 0.0
  efield_cart(2) = 0.0
  efield_cart(3) = $efield_amp
 /
ATOMIC_SPECIES
 $atom  30.974  $pseudo
ATOMIC_POSITIONS {bohr}
 $atom -0.699 0.000 2.008
 $atom 0.699 -0.000 -2.008 
 $atom -3.503 3.176 2.008
 $atom 3.503 -3.176 -2.008 
K_POINTS {automatic}
 $num_k $num_k 1 0 0 0
EOF

$ECHO "  running the scf calculation...\c"
if [ "$soc" == ".TRUE." ]; 
then
    if [ "$efield" == ".TRUE." ]; 
    then
        $PW_COMMAND < $prefix.scf.in > $prefix.scf.rel-efield.out
        check_failure $?
    else
        $PW_COMMAND < $prefix.scf.in > $prefix.scf.rel.out
        check_failure $?
    fi
else
    $PW_COMMAND < $prefix.scf.in > $prefix.scf.out
    check_failure $?
fi  
$ECHO " done"